[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
nn_yandex_art = "0.2.0"
anyhow = "1.0.100"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
base64 = "0.22.1"
dotenvy = "0.15.7"