[package]
name = "text_generation"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version =  "0.12.23", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.143"
core = { path = "../core" }
serde_as = "0.0.1"
serde_with = "3.14.0"
